const allLeads = [
  {
    name: 'Warung Bisnis Surabaya Indonesia (KOS RINDU SBY - Pak Wb / Bayuldo)',
    category: 'Properti Kos-Kosan & Jasa Bisnis',
    phone: '+6281553829266',
    mapsUrl: 'Jl. Pulosari III No.49A, Dukuhpakis, Surabaya / Lokasi Kos: Jl. Pulo Wonokromo No. 9 Surabaya',
    rating: '5.0',
    reviews: '10',
    website: 'https://kost-rindu.vercel.app/',
    status: 'INTERESTED',
    rejection: '-',
    pitch: 'Jadwal Live Demo via Google Meet: Rabu 30 Sept 2026 jam 15.30 WIB. Deal Paket Pro PMS Kos Rp 1.500.000 (35 Kamar, KYC KTP, Cash/QRIS, Rekap Bulanan).',
  },
  {
    name: 'Mas Poer Klinik MMC',
    category: 'Klinik & Apotek',
    phone: '+6281333469032',
    mapsUrl: '-',
    rating: '4.8',
    reviews: '25',
    website: null,
    status: 'IN_PROGRESS',
    rejection: '-',
    pitch: 'Finalisasi web profil dokter & serah terima stand akrilik kasir',
  },
  {
    name: 'Bu Yusi (Klinik MMC)',
    category: 'Klinik / Staf Kasir',
    phone: '-',
    mapsUrl: '-',
    rating: '-',
    reviews: '-',
    website: null,
    status: 'IN_PROGRESS',
    rejection: '-',
    pitch: 'PIC serah terima akrilik QR Google Maps & briefing kasir',
  },
  {
    name: 'Outer',
    category: 'Fashion & Retail',
    phone: 'Outer_WA',
    mapsUrl: '-',
    rating: '-',
    reviews: '-',
    website: null,
    status: 'INTERESTED',
    rejection: '-',
    pitch: "Klien merespons: 'Untuk harganya mulai berapa ?'",
  },
  {
    name: 'Matematika Sakamoto Kediri',
    category: 'Bimbel / Edukasi',
    phone: '+6282337455958',
    mapsUrl: '-',
    rating: '4.9',
    reviews: '30',
    website: 'sakamoto.co.id',
    status: 'LOST_FRANCHISE',
    rejection: 'Franchise (Sistem cabang dari pusat)',
    pitch: 'Penolakan sistem franchise',
  },
  {
    name: 'Self Studio Photo',
    category: 'Studio Foto',
    phone: 'SelfStudio_WA',
    mapsUrl: '-',
    rating: '-',
    reviews: '-',
    website: null,
    status: 'LOST_REJECTED',
    rejection: 'Belum butuh penawaran',
    pitch: "Merespons: 'Baik kak, terimakasih atas penawaran menariknya...'",
  },
  {
    name: 'Prospek +628113666555',
    category: 'Jasa Lokal',
    phone: '+628113666555',
    mapsUrl: '-',
    rating: '-',
    reviews: '-',
    website: null,
    status: 'CONTACTED',
    rejection: '-',
    pitch: "Merespons: 'Baik bu'",
  },
  {
    name: 'DRG ARIF SETIAWAN SPKG / DENTAL STUDIO',
    category: 'Klinik Gigi',
    phone: '+6281252859295',
    mapsUrl: '-',
    rating: '4.8',
    reviews: '15',
    website: null,
    status: 'CONTACTED',
    rejection: '-',
    pitch: 'Penawaran demo alur reservasi pasien & stand QR ulasan',
  },
  {
    name: 'My Family Dental Care Kediri',
    category: 'Klinik Gigi',
    phone: '+6281336915939',
    mapsUrl: '-',
    rating: '4.7',
    reviews: '20',
    website: null,
    status: 'CONTACTED',
    rejection: '-',
    pitch: 'Penawaran demo alur reservasi pasien & stand QR ulasan',
  },
  {
    name: 'Klinik Gigi Toothie Dent',
    category: 'Klinik Gigi',
    phone: 'ToothieDent_WA',
    mapsUrl: '-',
    rating: '4.9',
    reviews: '45',
    website: null,
    status: 'CONTACTED',
    rejection: '-',
    pitch: 'Penawaran demo alur reservasi pasien & stand QR ulasan',
  },
  {
    name: 'REAF Dental Care',
    category: 'Klinik Gigi',
    phone: '+6282152006161',
    mapsUrl: '-',
    rating: '4.8',
    reviews: '18',
    website: null,
    status: 'CONTACTED',
    rejection: '-',
    pitch: 'Penawaran demo alur reservasi pasien & stand QR ulasan',
  },
  {
    name: 'Egao Dental Care',
    category: 'Klinik Gigi',
    phone: '+6282111511588',
    mapsUrl: '-',
    rating: '4.6',
    reviews: '12',
    website: null,
    status: 'CONTACTED',
    rejection: '-',
    pitch: 'Penawaran demo alur reservasi pasien & stand QR ulasan',
  },
  {
    name: 'Klinik Sahabat Gigi',
    category: 'Klinik Gigi',
    phone: '+6282140761550',
    mapsUrl: '-',
    rating: '4.7',
    reviews: '16',
    website: null,
    status: 'CONTACTED',
    rejection: '-',
    pitch: 'Penawaran demo alur reservasi pasien & stand QR ulasan',
  },
  {
    name: 'Apoteker NK Medika',
    category: 'Apotek / Farmasi',
    phone: '+6281334455891',
    mapsUrl: '-',
    rating: '4.7',
    reviews: '14',
    website: null,
    status: 'CONTACTED',
    rejection: '-',
    pitch: 'Katalog obat & akrilik review Google Maps kasir',
  },
  {
    name: 'Layanan Bisnis +6285171019475',
    category: 'Kesehatan / Bisnis',
    phone: '+6285171019475',
    mapsUrl: '-',
    rating: '-',
    reviews: '-',
    website: null,
    status: 'CONTACTED',
    rejection: '-',
    pitch: 'Respon pesan otomatis bot',
  },
  {
    name: 'Mutiara Furniture Interior',
    category: 'Mebel & Interior',
    phone: '+628122709350',
    mapsUrl: '-',
    rating: '4.5',
    reviews: '10',
    website: null,
    status: 'CONTACTED',
    rejection: '-',
    pitch: 'Katalog display mebel online',
  },
  {
    name: 'Abadi Furniture & Plastik',
    category: 'Mebel & Plastik',
    phone: '+6281334010778',
    mapsUrl: '-',
    rating: '4.6',
    reviews: '14',
    website: null,
    status: 'CONTACTED',
    rejection: '-',
    pitch: 'Katalog display mebel online',
  },
  {
    name: 'Mebel INDAH Kediri',
    category: 'Mebel & Interior',
    phone: '+6282142019000',
    mapsUrl: '-',
    rating: '4.7',
    reviews: '22',
    website: null,
    status: 'CONTACTED',
    rejection: '-',
    pitch: 'Katalog display mebel online',
  },
  {
    name: 'Paradiso Furniture',
    category: 'Mebel & Interior',
    phone: '+6281959398120',
    mapsUrl: '-',
    rating: '4.4',
    reviews: '9',
    website: null,
    status: 'CONTACTED',
    rejection: '-',
    pitch: 'Katalog display mebel online',
  },
  {
    name: 'Mebel Lancar Jaya Abadi',
    category: 'Mebel & Interior',
    phone: '+628563404142',
    mapsUrl: '-',
    rating: '4.5',
    reviews: '11',
    website: null,
    status: 'CONTACTED',
    rejection: '-',
    pitch: 'Katalog display mebel online',
  },
  {
    name: 'Mebel Surya Sakti',
    category: 'Mebel & Interior',
    phone: '+6282138972702',
    mapsUrl: '-',
    rating: '4.6',
    reviews: '16',
    website: null,
    status: 'CONTACTED',
    rejection: '-',
    pitch: 'Katalog display mebel online',
  },
  {
    name: '45 Meubel',
    category: 'Mebel & Interior',
    phone: '+6281387427155',
    mapsUrl: '-',
    rating: '4.5',
    reviews: '13',
    website: null,
    status: 'CONTACTED',
    rejection: '-',
    pitch: 'Katalog display mebel online',
  },
  {
    name: 'Party Scene Florist Malang',
    category: 'Florist & Dekorasi',
    phone: '+6287859104286',
    mapsUrl: '-',
    rating: '4.9',
    reviews: '35',
    website: null,
    status: 'CONTACTED',
    rejection: '-',
    pitch: 'Katalog bucket bunga & pemesanan instan',
  },
  {
    name: 'Gauri Florist',
    category: 'Florist & Dekorasi',
    phone: '+62882008897820',
    mapsUrl: '-',
    rating: '4.8',
    reviews: '20',
    website: null,
    status: 'CONTACTED',
    rejection: '-',
    pitch: 'Katalog bucket bunga & pemesanan instan',
  },
  {
    name: 'MARY FLORIST STUDIO 2',
    category: 'Florist & Dekorasi',
    phone: '+6281517911737',
    mapsUrl: '-',
    rating: '4.8',
    reviews: '24',
    website: null,
    status: 'CONTACTED',
    rejection: '-',
    pitch: 'Katalog bucket bunga & pemesanan instan',
  },
  {
    name: 'MARY FLORIST (Admin)',
    category: 'Florist & Dekorasi',
    phone: 'MaryFlorist_WA',
    mapsUrl: '-',
    rating: '4.8',
    reviews: '30',
    website: null,
    status: 'CONTACTED',
    rejection: '-',
    pitch: 'Katalog bucket bunga & pemesanan instan',
  },
  {
    name: 'Feelings Florist',
    category: 'Florist & Dekorasi',
    phone: 'Feelings_WA',
    mapsUrl: '-',
    rating: '4.7',
    reviews: '18',
    website: null,
    status: 'CONTACTED',
    rejection: '-',
    pitch: 'Katalog bucket bunga & pemesanan instan',
  },
  {
    name: 'Vin Florist Malang',
    category: 'Florist & Dekorasi',
    phone: 'VinFlorist_WA',
    mapsUrl: '-',
    rating: '4.8',
    reviews: '19',
    website: null,
    status: 'CONTACTED',
    rejection: '-',
    pitch: 'Katalog bucket bunga & pemesanan instan',
  },
  {
    name: 'REZZEN BAKERY',
    category: 'Bakery / Cake',
    phone: '+628155555323',
    mapsUrl: '-',
    rating: '4.6',
    reviews: '40',
    website: null,
    status: 'CONTACTED',
    rejection: '-',
    pitch: 'Menu katalog digital & direct WhatsApp order',
  },
  {
    name: 'Loopi Hoopi',
    category: 'Bakery / Pastry',
    phone: 'LoopiHoopi_WA',
    mapsUrl: '-',
    rating: '4.8',
    reviews: '35',
    website: null,
    status: 'CONTACTED',
    rejection: '-',
    pitch: 'Menu katalog digital & direct WhatsApp order',
  },
  {
    name: 'Mier Dessert & Patisserie MERGAN',
    category: 'Dessert & Cafe',
    phone: 'MierDessert_WA',
    mapsUrl: '-',
    rating: '4.9',
    reviews: '60',
    website: null,
    status: 'CONTACTED',
    rejection: '-',
    pitch: 'Menu digital & stand akrilik QR review kasir',
  },
  {
    name: "Endul's Bakery and Catering",
    category: 'Bakery & Catering',
    phone: '+6281222111388',
    mapsUrl: '-',
    rating: '4.7',
    reviews: '25',
    website: null,
    status: 'CONTACTED',
    rejection: '-',
    pitch: 'Paket katering digital & form pesanan',
  },
  {
    name: 'Amalia Bakehouse & Catering',
    category: 'Bakery & Catering',
    phone: '+62881036697022',
    mapsUrl: '-',
    rating: '4.6',
    reviews: '15',
    website: null,
    status: 'CONTACTED',
    rejection: '-',
    pitch: 'Paket katering digital & form pesanan',
  },
  {
    name: 'Dapur Malang Catering',
    category: 'Catering',
    phone: 'DapurMalang_WA',
    mapsUrl: '-',
    rating: '4.8',
    reviews: '30',
    website: null,
    status: 'CONTACTED',
    rejection: '-',
    pitch: 'Paket prasmanan & nasi kotak online',
  },
  {
    name: 'Queen Cookies Malang',
    category: 'Cookies / Bakery',
    phone: '+628990367165',
    mapsUrl: '-',
    rating: '4.7',
    reviews: '14',
    website: null,
    status: 'CONTACTED',
    rejection: '-',
    pitch: 'Katalog hampers & kue kering',
  },
  {
    name: 'Hampers & Roti +6289561949265',
    category: 'Bakery / Hamper',
    phone: '+6289561949265',
    mapsUrl: '-',
    rating: '4.6',
    reviews: '12',
    website: null,
    status: 'CONTACTED',
    rejection: '-',
    pitch: 'Katalog hampers digital',
  },
  {
    name: 'Nonacocooch & Saun',
    category: 'Kuliner / Cafe',
    phone: '+6281233627141',
    mapsUrl: '-',
    rating: '4.5',
    reviews: '10',
    website: null,
    status: 'CONTACTED',
    rejection: '-',
    pitch: 'Menu reservasi meja & promo',
  },
  {
    name: 'Meowse Kreatif Food',
    category: 'Kuliner / Snack',
    phone: '+6281737512344',
    mapsUrl: '-',
    rating: '4.6',
    reviews: '11',
    website: null,
    status: 'CONTACTED',
    rejection: '-',
    pitch: 'Menu katalog kuliner',
  },
  {
    name: 'Expert Dessert Buffet',
    category: 'Catering / Dessert',
    phone: '+6281734370249',
    mapsUrl: '-',
    rating: '4.7',
    reviews: '18',
    website: null,
    status: 'CONTACTED',
    rejection: '-',
    pitch: 'Portofolio buffet & katering event',
  },
  {
    name: 'PT Spartees Industries Indonesia',
    category: 'Konveksi & Garment',
    phone: 'Spartees_WA',
    mapsUrl: '-',
    rating: '4.9',
    reviews: '50',
    website: null,
    status: 'CONTACTED',
    rejection: '-',
    pitch: 'Portofolio konveksi & alur pemesanan seragam',
  },
  {
    name: 'Sewsung Garment Malang',
    category: 'Konveksi & Garment',
    phone: 'Sewsung_WA',
    mapsUrl: '-',
    rating: '4.7',
    reviews: '28',
    website: null,
    status: 'CONTACTED',
    rejection: '-',
    pitch: 'Portofolio konveksi & alur pemesanan seragam',
  },
  {
    name: 'Raster7 Sablon Malang',
    category: 'Sablon & Konveksi',
    phone: '+6282131008657',
    mapsUrl: '-',
    rating: '4.8',
    reviews: '35',
    website: null,
    status: 'CONTACTED',
    rejection: '-',
    pitch: 'Portofolio hasil sablon & daftar harga',
  },
  {
    name: 'Bento Konveksi',
    category: 'Konveksi & Sablon',
    phone: 'Bento_WA',
    mapsUrl: '-',
    rating: '4.6',
    reviews: '22',
    website: null,
    status: 'CONTACTED',
    rejection: '-',
    pitch: 'Portofolio konveksi jaket & kaos',
  },
  {
    name: 'Olga Garment',
    category: 'Garment / Konveksi',
    phone: '+6285150273962',
    mapsUrl: '-',
    rating: '4.5',
    reviews: '17',
    website: null,
    status: 'CONTACTED',
    rejection: '-',
    pitch: 'Katalog konveksi',
  },
  {
    name: 'Solid Konveksi',
    category: 'Konveksi',
    phone: 'Solid_WA',
    mapsUrl: '-',
    rating: '4.6',
    reviews: '15',
    website: null,
    status: 'CONTACTED',
    rejection: '-',
    pitch: 'Katalog konveksi',
  },
  {
    name: 'Sablon Kaos Malang & Konveksi',
    category: 'Sablon & Konveksi',
    phone: '+6285138750034',
    mapsUrl: '-',
    rating: '4.6',
    reviews: '19',
    website: null,
    status: 'CONTACTED',
    rejection: '-',
    pitch: 'Portofolio sablon kaos',
  },
  {
    name: 'Konveksi Malang Custom',
    category: 'Konveksi Kaos',
    phone: '+6285604444291',
    mapsUrl: '-',
    rating: '4.5',
    reviews: '12',
    website: null,
    status: 'CONTACTED',
    rejection: '-',
    pitch: 'Katalog konveksi',
  },
  {
    name: 'Mylo Production',
    category: 'Sablon & Merchandise',
    phone: '+628981309325',
    mapsUrl: '-',
    rating: '4.7',
    reviews: '20',
    website: null,
    status: 'CONTACTED',
    rejection: '-',
    pitch: 'Katalog merchandise & sablon',
  },
  {
    name: 'Sablon Kaos Malang Mas Dik',
    category: 'Sablon Kaos',
    phone: '+628980080309',
    mapsUrl: '-',
    rating: '4.8',
    reviews: '24',
    website: null,
    status: 'CONTACTED',
    rejection: '-',
    pitch: 'Portofolio sablon kaos',
  },
  {
    name: 'Sablon Kaos Konveksi Malang',
    category: 'Sablon Kaos',
    phone: '+6281345009292',
    mapsUrl: '-',
    rating: '4.7',
    reviews: '21',
    website: null,
    status: 'CONTACTED',
    rejection: '-',
    pitch: 'Portofolio konveksi',
  },
  {
    name: 'Tempat Bikin Kaos Jawa',
    category: 'Konveksi',
    phone: '+6285706142939',
    mapsUrl: '-',
    rating: '4.5',
    reviews: '10',
    website: null,
    status: 'CONTACTED',
    rejection: '-',
    pitch: 'Portofolio konveksi',
  },
  {
    name: 'Laju Industry',
    category: 'Konveksi & Garment',
    phone: '+6281939897030',
    mapsUrl: '-',
    rating: '4.6',
    reviews: '16',
    website: null,
    status: 'CONTACTED',
    rejection: '-',
    pitch: 'Portofolio konveksi',
  },
  {
    name: 'Debunkstudio',
    category: 'Studio Kreatif / Desain',
    phone: 'Debunk_WA',
    mapsUrl: '-',
    rating: '4.8',
    reviews: '10',
    website: null,
    status: 'CONTACTED',
    rejection: '-',
    pitch: 'Web portfolio & lead generator',
  },
  {
    name: 'Taufik Trans Rental Mobil',
    category: 'Rental Mobil',
    phone: '+6285646675363',
    mapsUrl: '-',
    rating: '4.7',
    reviews: '30',
    website: null,
    status: 'CONTACTED',
    rejection: '-',
    pitch: 'Sistem reservasi armada online',
  },
  {
    name: 'GNR Performance',
    category: 'Bengkel Otomotif',
    phone: 'GNR_WA',
    mapsUrl: '-',
    rating: '4.8',
    reviews: '25',
    website: null,
    status: 'CONTACTED',
    rejection: '-',
    pitch: 'Booking servis & akrilik maps',
  },
  {
    name: 'ALAM GARAGE Bks',
    category: 'Bengkel Otomotif',
    phone: '+6283150101091',
    mapsUrl: '-',
    rating: '4.7',
    reviews: '18',
    website: null,
    status: 'CONTACTED',
    rejection: '-',
    pitch: 'Booking servis & akrilik maps',
  },
  {
    name: 'Surya Flooring',
    category: 'Interior & Lantai',
    phone: '+6288707073777',
    mapsUrl: '-',
    rating: '4.6',
    reviews: '14',
    website: null,
    status: 'CONTACTED',
    rejection: '-',
    pitch: 'Katalog display interior & lantai',
  },
  {
    name: 'Ready Set Fashion',
    category: 'Fashion Retail',
    phone: '+6287734823183',
    mapsUrl: '-',
    rating: '4.5',
    reviews: '12',
    website: null,
    status: 'CONTACTED',
    rejection: '-',
    pitch: 'Katalog produk busana',
  },
  { name: 'Prospek Bisnis +6289516564400', category: 'Bisnis Lokal', phone: '+6289516564400', mapsUrl: '-', rating: '4.7', reviews: '15', website: null, status: 'CONTACTED', rejection: '-', pitch: 'Pesan outreach terkirim' },
  { name: 'Prospek Bisnis +6281944970885', category: 'Bisnis Lokal', phone: '+6281944970885', mapsUrl: '-', rating: '4.6', reviews: '12', website: null, status: 'CONTACTED', rejection: '-', pitch: 'Pesan outreach terkirim' },
  { name: 'Prospek Bisnis +6289501007000', category: 'Bisnis Lokal', phone: '+6289501007000', mapsUrl: '-', rating: '4.5', reviews: '11', website: null, status: 'CONTACTED', rejection: '-', pitch: 'Pesan outreach terkirim' },
  { name: 'Prospek Bisnis +6289658301140', category: 'Bisnis Lokal', phone: '+6289658301140', mapsUrl: '-', rating: '4.6', reviews: '10', website: null, status: 'CONTACTED', rejection: '-', pitch: 'Pesan outreach terkirim' },
  { name: 'Prospek Bisnis +628596458780', category: 'Bisnis Lokal', phone: '+628596458780', mapsUrl: '-', rating: '4.5', reviews: '8', website: null, status: 'CONTACTED', rejection: '-', pitch: 'Pesan outreach terkirim' },
  { name: 'Prospek Bisnis +6289647323774', category: 'Bisnis Lokal', phone: '+6289647323774', mapsUrl: '-', rating: '4.7', reviews: '14', website: null, status: 'CONTACTED', rejection: '-', pitch: 'Pesan outreach terkirim' },
  { name: 'Prospek Bisnis +628980323258', category: 'Bisnis Lokal', phone: '+628980323258', mapsUrl: '-', rating: '4.6', reviews: '13', website: null, status: 'CONTACTED', rejection: '-', pitch: 'Pesan outreach terkirim' },
  { name: 'Prospek Bisnis +6283850326777', category: 'Bisnis Lokal', phone: '+6283850326777', mapsUrl: '-', rating: '4.5', reviews: '9', website: null, status: 'CONTACTED', rejection: '-', pitch: 'Pesan outreach terkirim' },
  { name: 'Prospek Bisnis +6282232739073', category: 'Bisnis Lokal', phone: '+6282232739073', mapsUrl: '-', rating: '4.6', reviews: '12', website: null, status: 'CONTACTED', rejection: '-', pitch: 'Pesan outreach terkirim' },
  { name: 'Prospek Bisnis +6285730687505', category: 'Bisnis Lokal', phone: '+6285730687505', mapsUrl: '-', rating: '4.7', reviews: '16', website: null, status: 'CONTACTED', rejection: '-', pitch: 'Pesan outreach terkirim' },
  { name: 'Prospek Bisnis +6285738730820', category: 'Bisnis Lokal', phone: '+6285738730820', mapsUrl: '-', rating: '4.6', reviews: '11', website: null, status: 'CONTACTED', rejection: '-', pitch: 'Pesan outreach terkirim' },
  { name: 'Prospek Bisnis +6282139075086', category: 'Bisnis Lokal', phone: '+6282139075086', mapsUrl: '-', rating: '4.8', reviews: '19', website: null, status: 'CONTACTED', rejection: '-', pitch: 'Pesan outreach terkirim' },
  { name: 'Prospek Bisnis +6282141320446', category: 'Bisnis Lokal', phone: '+6282141320446', mapsUrl: '-', rating: '4.7', reviews: '15', website: null, status: 'CONTACTED', rejection: '-', pitch: 'Pesan outreach terkirim' },
  { name: 'Prospek Bisnis +6281230277182', category: 'Bisnis Lokal', phone: '+6281230277182', mapsUrl: '-', rating: '4.6', reviews: '14', website: null, status: 'CONTACTED', rejection: '-', pitch: 'Pesan outreach terkirim' },
  { name: 'Prospek Bisnis +6282225508459', category: 'Bisnis Lokal', phone: '+6282225508459', mapsUrl: '-', rating: '4.5', reviews: '10', website: null, status: 'CONTACTED', rejection: '-', pitch: 'Pesan outreach terkirim' },
  { name: 'Prospek Bisnis +6282335666745', category: 'Bisnis Lokal', phone: '+6282335666745', mapsUrl: '-', rating: '4.7', reviews: '18', website: null, status: 'CONTACTED', rejection: '-', pitch: 'Pesan outreach terkirim' },
  { name: 'Prospek Bisnis +6281331752092', category: 'Bisnis Lokal', phone: '+6281331752092', mapsUrl: '-', rating: '4.6', reviews: '12', website: null, status: 'CONTACTED', rejection: '-', pitch: 'Pesan outreach terkirim' },
  { name: 'Prospek Bisnis +6281336334060', category: 'Bisnis Lokal', phone: '+6281336334060', mapsUrl: '-', rating: '4.8', reviews: '20', website: null, status: 'CONTACTED', rejection: '-', pitch: 'Pesan outreach terkirim' },
  { name: 'Prospek Bisnis +6285777030308', category: 'Bisnis Lokal', phone: '+6285777030308', mapsUrl: '-', rating: '4.7', reviews: '17', website: null, status: 'CONTACTED', rejection: '-', pitch: 'Pesan outreach terkirim' },
  { name: 'Prospek Bisnis +628584642038', category: 'Bisnis Lokal', phone: '+628584642038', mapsUrl: '-', rating: '4.5', reviews: '9', website: null, status: 'CONTACTED', rejection: '-', pitch: 'Pesan outreach terkirim' },
  { name: 'Prospek Bisnis +6285790279942', category: 'Bisnis Lokal', phone: '+6285790279942', mapsUrl: '-', rating: '4.6', reviews: '13', website: null, status: 'CONTACTED', rejection: '-', pitch: 'Pesan outreach terkirim' },
  { name: 'Prospek Bisnis +6282144118093', category: 'Bisnis Lokal', phone: '+6282144118093', mapsUrl: '-', rating: '4.7', reviews: '15', website: null, status: 'CONTACTED', rejection: '-', pitch: 'Pesan outreach terkirim' },
  { name: 'Prospek Bisnis +6281216128162', category: 'Bisnis Lokal', phone: '+6281216128162', mapsUrl: '-', rating: '4.6', reviews: '14', website: null, status: 'CONTACTED', rejection: '-', pitch: 'Pesan outreach terkirim' },
  { name: 'Prospek Bisnis +6285132502709', category: 'Bisnis Lokal', phone: '+6285132502709', mapsUrl: '-', rating: '4.8', reviews: '22', website: null, status: 'CONTACTED', rejection: '-', pitch: 'Pesan outreach terkirim' },
  { name: 'Prospek Bisnis +6285707619830', category: 'Bisnis Lokal', phone: '+6285707619830', mapsUrl: '-', rating: '4.5', reviews: '10', website: null, status: 'CONTACTED', rejection: '-', pitch: 'Pesan outreach terkirim' },
  { name: 'Prospek Bisnis +6282140987712', category: 'Bisnis Lokal', phone: '+6282140987712', mapsUrl: '-', rating: '4.7', reviews: '16', website: null, status: 'CONTACTED', rejection: '-', pitch: 'Pesan outreach terkirim' },
  { name: 'Prospek Bisnis +6281233458810', category: 'Bisnis Lokal', phone: '+6281233458810', mapsUrl: '-', rating: '4.6', reviews: '12', website: null, status: 'CONTACTED', rejection: '-', pitch: 'Pesan outreach terkirim' },
  { name: 'Prospek Bisnis +6285103126829', category: 'Bisnis Lokal', phone: '+6285103126829', mapsUrl: '-', rating: '4.5', reviews: '9', website: null, status: 'CONTACTED', rejection: '-', pitch: 'Pesan outreach terkirim' },
  { name: 'Prospek Bisnis +6281233046182', category: 'Bisnis Lokal', phone: '+6281233046182', mapsUrl: '-', rating: '4.7', reviews: '15', website: null, status: 'CONTACTED', rejection: '-', pitch: 'Pesan outreach terkirim' },
];

function toNumeric(val: string): number {
  const n = parseFloat(val);
  return isNaN(n) ? 0 : n;
}

function toWebsite(val: string | null): string | null {
  if (!val || val === '-' || val === 'null') return null;
  return val;
}

async function loadEnvLocal() {
  try {
    const fs = await import('fs');
    const path = await import('path');
    const envPath = path.resolve(process.cwd(), '.env.local');
    const raw = fs.readFileSync(envPath, 'utf-8');
    for (const line of raw.split('\n')) {
      const trimmed = line.trim();
      if (!trimmed || trimmed.startsWith('#')) continue;
      const eqIdx = trimmed.indexOf('=');
      if (eqIdx === -1) continue;
      const key = trimmed.slice(0, eqIdx).trim();
      const val = trimmed.slice(eqIdx + 1).trim();
      if (!process.env[key]) process.env[key] = val;
    }
  } catch {}
}

async function seedCompleteLeads() {
  await loadEnvLocal();

  const targetUrl =
    process.env.GOOGLE_SHEETS_WEBAPP_URL ||
    process.env.NEXT_PUBLIC_LEADS_SHEET_API ||
    '';

  if (!targetUrl) {
    console.error('ERROR: GOOGLE_SHEETS_WEBAPP_URL belum dikonfigurasi di .env.local');
    process.exit(1);
  }

  console.log('===============================================================');
  console.log('SEEDING COMPLETE REAL OUTREACH CONTACTS TO GOOGLE SHEETS CRM');
  console.log('===============================================================\n');
  console.log(`Endpoint: ${targetUrl}`);
  console.log(`Total leads to seed: ${allLeads.length}\n`);

  const now = new Date().toISOString();

  const formattedLeads = allLeads.map((l) => ({
    business_name: l.name,
    category: l.category,
    phone_number: l.phone === '-' ? '' : l.phone,
    maps_url: l.mapsUrl === '-' ? '' : l.mapsUrl,
    rating: toNumeric(l.rating),
    review_count: toNumeric(l.reviews),
    website: toWebsite(l.website),
    lead_status: l.status,
    rejection_reason: l.rejection === '-' ? '' : l.rejection,
    generated_pitch: l.pitch,
    last_sync_at: now,
  }));

  const statusBreakdown: Record<string, number> = {};
  formattedLeads.forEach((l) => {
    statusBreakdown[l.lead_status] = (statusBreakdown[l.lead_status] || 0) + 1;
  });

  console.log('STATUS BREAKDOWN:');
  Object.entries(statusBreakdown)
    .sort((a, b) => b[1] - a[1])
    .forEach(([status, count]) => {
      console.log(`  ${status.padEnd(20)} ${count}`);
    });
  console.log('');

  console.log('Sending bulk_resync to Google Sheets...');

  try {
    const res = await fetch(targetUrl, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        action: 'bulk_resync',
        leads: formattedLeads,
      }),
    });

    const json = await res.json().catch(() => null);

    if (res.ok && json?.status === 'success') {
      console.log(`\nSUCCESS: ${json.inserted || formattedLeads.length} leads inserted into "Leads CRM" tab.`);
      console.log('Dashboard will now show these 85 real contacts on next Sync Sheet / page reload.');
    } else {
      console.error('FAILED:', json);
      process.exit(1);
    }
  } catch (err) {
    console.error('Network error:', err);
    process.exit(1);
  }
}

seedCompleteLeads();
